/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcatalog;

import javax.swing.JOptionPane;

/**
 *
 * @author sasmith10
 */
public class BreadsJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DrinkJDialog
     */
    public BreadsJDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        breadsJPanel = new javax.swing.JPanel();
        briocheRB = new javax.swing.JRadioButton();
        sourdoughRB = new javax.swing.JRadioButton();
        ryeRB = new javax.swing.JRadioButton();
        quitlJLabel1 = new javax.swing.JButton();
        viewJLabel1 = new javax.swing.JButton();
        clearJLabel1 = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        breadsJPanel.setBackground(new java.awt.Color(204, 0, 0));
        breadsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Bread Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Showcard Gothic", 2, 46), new java.awt.Color(255, 255, 0))); // NOI18N

        briocheRB.setBackground(new java.awt.Color(255, 255, 0));
        briocheRB.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        briocheRB.setText("Brioche");
        briocheRB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        briocheRB.setBorderPainted(true);
        briocheRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                briocheRBActionPerformed(evt);
            }
        });

        sourdoughRB.setBackground(new java.awt.Color(255, 255, 0));
        sourdoughRB.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        sourdoughRB.setText("Sourdough");
        sourdoughRB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        sourdoughRB.setBorderPainted(true);
        sourdoughRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourdoughRBActionPerformed(evt);
            }
        });

        ryeRB.setBackground(new java.awt.Color(255, 255, 0));
        ryeRB.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        ryeRB.setText("Rye");
        ryeRB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        ryeRB.setBorderPainted(true);
        ryeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ryeRBActionPerformed(evt);
            }
        });

        quitlJLabel1.setBackground(new java.awt.Color(255, 255, 0));
        quitlJLabel1.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        quitlJLabel1.setText("Quit");
        quitlJLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        quitlJLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitlJLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitlJLabel1ActionPerformed(evt);
            }
        });

        viewJLabel1.setBackground(new java.awt.Color(255, 255, 0));
        viewJLabel1.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        viewJLabel1.setText("View Item");
        viewJLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        viewJLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewJLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJLabel1ActionPerformed(evt);
            }
        });

        clearJLabel1.setBackground(new java.awt.Color(255, 255, 0));
        clearJLabel1.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        clearJLabel1.setText("Clear");
        clearJLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        clearJLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearJLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJLabel1ActionPerformed(evt);
            }
        });

        mainMenuButton.setBackground(new java.awt.Color(255, 255, 0));
        mainMenuButton.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        mainMenuButton.setText("Main Menu");
        mainMenuButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        mainMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food Catalog Pictures/Brioche.png"))); // NOI18N
        jLabel11.setText("Brioche");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food Catalog Pictures/Rye.png"))); // NOI18N
        jLabel12.setText("Rye");
        jLabel12.setToolTipText("");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food Catalog Pictures/Sourdough.png"))); // NOI18N
        jLabel10.setText("jLabel4");

        javax.swing.GroupLayout breadsJPanelLayout = new javax.swing.GroupLayout(breadsJPanel);
        breadsJPanel.setLayout(breadsJPanelLayout);
        breadsJPanelLayout.setHorizontalGroup(
            breadsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, breadsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(breadsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitlJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(336, 336, 336))
            .addGroup(breadsJPanelLayout.createSequentialGroup()
                .addGroup(breadsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(breadsJPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(briocheRB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(ryeRB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(sourdoughRB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(breadsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        breadsJPanelLayout.setVerticalGroup(
            breadsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(breadsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(breadsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(breadsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ryeRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(briocheRB)
                    .addComponent(sourdoughRB))
                .addGap(36, 36, 36)
                .addComponent(viewJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quitlJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(breadsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(breadsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed

        dispose();
        MainMenuJDialog obj = new MainMenuJDialog();
        obj.setVisible(true);
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void clearJLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJLabel1ActionPerformed
        //      clears all selections and text fields
        briocheRB.setSelected(false);
        ryeRB.setSelected(false);
        sourdoughRB.setSelected(false);
    }//GEN-LAST:event_clearJLabel1ActionPerformed

    private void viewJLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJLabel1ActionPerformed

        if (briocheRB.isSelected()){
            JOptionPane.showMessageDialog(null, "Brioche is a bread of French origin that is similar to a highly enriched pastry, "
                + "\nand whose high egg and butter content give it a rich and tender crumb. "
                + "\nBrioche is considered a Viennoiserie, in that it is made in the same basic way as bread, "
                + "\nbut has the richer aspect of a pastry because of the extra addition of eggs,"
                + "\nbutter, liquid (milk, water, cream, and, sometimes, brandy) and occasionally some sugar.");
            dispose();
            BreadsJDialog obj = new BreadsJDialog();
            obj.setVisible(true);
        }
        else if(ryeRB.isSelected()){
            JOptionPane.showMessageDialog(null, "Rye bread is a type of bread made with various proportions of flour from rye grain. "
                + "\nIt can be light or dark in color, depending on the type of flour used and the addition of coloring agents, "
                + "\nand is typically denser than bread made from wheat flour.");
            dispose();
            BreadsJDialog obj = new BreadsJDialog();
            obj.setVisible(true);
        }
        else if(sourdoughRB.isSelected()){
            JOptionPane.showMessageDialog(null, "Sourdough bread is made by the fermentation of dough using naturally occurring lactobacilli and yeast."
                + "\nSourdough bread has a more sour taste and better inherent keeping qualities than breads made with baker's yeast, "
                + "\ndue to the lactic acid produced by the lactobacilli.");
            dispose();
            BreadsJDialog obj = new BreadsJDialog();
            obj.setVisible(true);
        }
    }//GEN-LAST:event_viewJLabel1ActionPerformed

    private void quitlJLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitlJLabel1ActionPerformed
        // cancel
        System.exit(0);
    }//GEN-LAST:event_quitlJLabel1ActionPerformed

    private void ryeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ryeRBActionPerformed
        // changing radio buttons so only one is selected

        if (ryeRB.isSelected()){
            briocheRB.setSelected(false);
            sourdoughRB.setSelected(false);
        }
    }//GEN-LAST:event_ryeRBActionPerformed

    private void sourdoughRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourdoughRBActionPerformed
        // changing radio buttons so only one is selected
        if (sourdoughRB.isSelected()){
            ryeRB.setSelected(false);
            briocheRB.setSelected(false);
        }
    }//GEN-LAST:event_sourdoughRBActionPerformed

    private void briocheRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_briocheRBActionPerformed
        // changing radio buttons to select only one
        if (briocheRB.isSelected()){
            ryeRB.setSelected(false);
            sourdoughRB.setSelected(false);
        }
    }//GEN-LAST:event_briocheRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BreadsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BreadsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BreadsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BreadsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BreadsJDialog().setVisible(true);

                    }
                });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel breadsJPanel;
    private javax.swing.JRadioButton briocheRB;
    private javax.swing.JButton clearJLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton quitlJLabel1;
    private javax.swing.JRadioButton ryeRB;
    private javax.swing.JRadioButton sourdoughRB;
    private javax.swing.JButton viewJLabel1;
    // End of variables declaration//GEN-END:variables
}
