
package foodcatalog;

import javax.swing.JOptionPane;


public class MainMenuJDialog extends javax.swing.JDialog {
   
    public MainMenuJDialog() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        breadToggleButton = new javax.swing.JToggleButton();
        meatsToggleButton = new javax.swing.JToggleButton();
        pastriesToggleButton = new javax.swing.JToggleButton();
        quitButton = new javax.swing.JButton();
        vendingMachine = new javax.swing.JLabel();
        fruitToggleButton1 = new javax.swing.JToggleButton();
        saladToggleButton1 = new javax.swing.JToggleButton();
        vendingMachineJMenuBar = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        helpJMenuItem = new javax.swing.JMenuItem();
        editJMenu = new javax.swing.JMenu();
        nothingJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 204, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 0)));

        breadToggleButton.setBackground(new java.awt.Color(255, 255, 0));
        breadToggleButton.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        breadToggleButton.setText("Breads");
        breadToggleButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        breadToggleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        breadToggleButton.setPreferredSize(new java.awt.Dimension(101, 23));
        breadToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadToggleButtonActionPerformed(evt);
            }
        });

        meatsToggleButton.setBackground(new java.awt.Color(255, 255, 0));
        meatsToggleButton.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        meatsToggleButton.setText("Meats");
        meatsToggleButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        meatsToggleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meatsToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatsToggleButtonActionPerformed(evt);
            }
        });

        pastriesToggleButton.setBackground(new java.awt.Color(255, 255, 0));
        pastriesToggleButton.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        pastriesToggleButton.setText("Pastries");
        pastriesToggleButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        pastriesToggleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pastriesToggleButton.setPreferredSize(new java.awt.Dimension(101, 23));
        pastriesToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastriesToggleButtonActionPerformed(evt);
            }
        });

        quitButton.setBackground(new java.awt.Color(255, 255, 0));
        quitButton.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        quitButton.setText("Quit");
        quitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        quitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitButton.setMaximumSize(new java.awt.Dimension(39, 19));
        quitButton.setMinimumSize(new java.awt.Dimension(39, 19));
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        vendingMachine.setBackground(new java.awt.Color(255, 255, 0));
        vendingMachine.setFont(new java.awt.Font("Showcard Gothic", 2, 46)); // NOI18N
        vendingMachine.setForeground(new java.awt.Color(255, 204, 0));
        vendingMachine.setText("FOOD CATALOG");
        vendingMachine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        vendingMachine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fruitToggleButton1.setBackground(new java.awt.Color(255, 255, 0));
        fruitToggleButton1.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        fruitToggleButton1.setText("Fruits");
        fruitToggleButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        fruitToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fruitToggleButton1.setPreferredSize(new java.awt.Dimension(101, 23));
        fruitToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitToggleButton1ActionPerformed(evt);
            }
        });

        saladToggleButton1.setBackground(new java.awt.Color(255, 255, 0));
        saladToggleButton1.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        saladToggleButton1.setText("Salads");
        saladToggleButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        saladToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saladToggleButton1.setPreferredSize(new java.awt.Dimension(101, 23));
        saladToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saladToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(saladToggleButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(breadToggleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fruitToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pastriesToggleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(meatsToggleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(vendingMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(vendingMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breadToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(saladToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(meatsToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fruitToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pastriesToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        vendingMachineJMenuBar.setBackground(new java.awt.Color(255, 255, 255));
        vendingMachineJMenuBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 51)));

        fileJMenu.setBackground(new java.awt.Color(255, 204, 0));
        fileJMenu.setText("File");
        fileJMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        helpJMenuItem.setText("Help");
        helpJMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(helpJMenuItem);

        vendingMachineJMenuBar.add(fileJMenu);

        editJMenu.setText("Edit");
        editJMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nothingJMenuItem.setText("Nothing, Don't click this!");
        nothingJMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nothingJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nothingJMenuItemActionPerformed(evt);
            }
        });
        editJMenu.add(nothingJMenuItem);

        vendingMachineJMenuBar.add(editJMenu);

        setJMenuBar(vendingMachineJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pastriesToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastriesToggleButtonActionPerformed
    JOptionPane.showMessageDialog(null, "Please select your pastry item and then you will get information about said item.","Pastry Menu",JOptionPane.PLAIN_MESSAGE);
    dispose();
    PastriesJDialog obj = new PastriesJDialog();
    obj.setVisible(true);

    }//GEN-LAST:event_pastriesToggleButtonActionPerformed

    private void breadToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breadToggleButtonActionPerformed
    JOptionPane.showMessageDialog(null, "Please select your bread item and then you will get information about said item.","Bread Menu",JOptionPane.PLAIN_MESSAGE);
    dispose();    
    BreadsJDialog obj = new BreadsJDialog();
    obj.setVisible(true);

    }//GEN-LAST:event_breadToggleButtonActionPerformed

    private void meatsToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatsToggleButtonActionPerformed
    JOptionPane.showMessageDialog(null, "Please select your meat item and then you will get information about said item.","Meat Menu",JOptionPane.PLAIN_MESSAGE);
    dispose();
    MeatsJDialog obj = new MeatsJDialog();
    obj.setVisible(true);

    }//GEN-LAST:event_meatsToggleButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        
    System.exit(0);
    
    }//GEN-LAST:event_quitButtonActionPerformed

    private void helpJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpJMenuItemActionPerformed

    JOptionPane.showMessageDialog
			(null, "This is how you use the Food Catalog." + "\n\n" 
                               + "Step 1. You choose an option on the Main Menu."
                               + "\nStep 2. You choose an option on the screen you were taken too only if you didn't choose quit."
                               + "\n\nThese next two steps can be done in any order."
                               + "\n\nStep 3. Decide on the item of your choice or quit the menu."
                               + "\nStep 4. You can use the view item button to obtain information about your desired item."
                               + "\n\nAnd that was how to use the Food Catalog program with Steven, your helper!"
                               + "\nThanks!"
			,"Food Catalog Tips", JOptionPane.QUESTION_MESSAGE);

    }//GEN-LAST:event_helpJMenuItemActionPerformed

    private void nothingJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nothingJMenuItemActionPerformed
    
    JOptionPane.showMessageDialog(null, "This is actually nothing, lol");
    }//GEN-LAST:event_nothingJMenuItemActionPerformed

    private void fruitToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitToggleButton1ActionPerformed
    JOptionPane.showMessageDialog(null, "Please select your fruit item and then you will get information about said item.","Fruit Menu",JOptionPane.PLAIN_MESSAGE);
    dispose();
    FruitsJDialog obj = new FruitsJDialog();
    obj.setVisible(true);

    }//GEN-LAST:event_fruitToggleButton1ActionPerformed

    private void saladToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saladToggleButton1ActionPerformed
    JOptionPane.showMessageDialog(null, "Please select your salad item and then you will get information about said item.","Salad Menu",JOptionPane.PLAIN_MESSAGE);
    dispose();
    SaladsJDialog obj = new SaladsJDialog();
    obj.setVisible(true);
    }//GEN-LAST:event_saladToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuJDialog().setVisible(true);

                    }
                });
            }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton breadToggleButton;
    private javax.swing.JMenu editJMenu;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JToggleButton fruitToggleButton1;
    private javax.swing.JMenuItem helpJMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton meatsToggleButton;
    private javax.swing.JMenuItem nothingJMenuItem;
    private javax.swing.JToggleButton pastriesToggleButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JToggleButton saladToggleButton1;
    private javax.swing.JLabel vendingMachine;
    private javax.swing.JMenuBar vendingMachineJMenuBar;
    // End of variables declaration//GEN-END:variables

}