/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcatalog;

import javax.swing.JOptionPane;

/**
 *
 * @author sasmith10
 */
public class MeatsJDialog extends javax.swing.JDialog {

    /**
     * Creates new form MiscellaneousJDialog
     */
    public MeatsJDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meatsJPanel = new javax.swing.JPanel();
        lambMuttonRB = new javax.swing.JRadioButton();
        duckRB = new javax.swing.JRadioButton();
        chickenRB = new javax.swing.JRadioButton();
        quitlJLabel3 = new javax.swing.JButton();
        viewJLabel4 = new javax.swing.JButton();
        clearJLabel4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        mainMenuButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        meatsJPanel.setBackground(new java.awt.Color(204, 0, 0));
        meatsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Meat Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Showcard Gothic", 2, 46), new java.awt.Color(255, 255, 0))); // NOI18N

        lambMuttonRB.setBackground(new java.awt.Color(255, 255, 0));
        lambMuttonRB.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        lambMuttonRB.setText("Lamb/Mutton");
        lambMuttonRB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        lambMuttonRB.setBorderPainted(true);
        lambMuttonRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lambMuttonRBActionPerformed(evt);
            }
        });

        duckRB.setBackground(new java.awt.Color(255, 255, 0));
        duckRB.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        duckRB.setText("Duck");
        duckRB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        duckRB.setBorderPainted(true);
        duckRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duckRBActionPerformed(evt);
            }
        });

        chickenRB.setBackground(new java.awt.Color(255, 255, 0));
        chickenRB.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        chickenRB.setText("Chicken");
        chickenRB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        chickenRB.setBorderPainted(true);
        chickenRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenRBActionPerformed(evt);
            }
        });

        quitlJLabel3.setBackground(new java.awt.Color(255, 255, 0));
        quitlJLabel3.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        quitlJLabel3.setText("Quit");
        quitlJLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        quitlJLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitlJLabel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitlJLabel3ActionPerformed(evt);
            }
        });

        viewJLabel4.setBackground(new java.awt.Color(255, 255, 0));
        viewJLabel4.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        viewJLabel4.setText("View Item");
        viewJLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        viewJLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewJLabel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJLabel4ActionPerformed(evt);
            }
        });

        clearJLabel4.setBackground(new java.awt.Color(255, 255, 0));
        clearJLabel4.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        clearJLabel4.setText("Clear");
        clearJLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        clearJLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearJLabel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJLabel4ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food Catalog Pictures/Duck.jpg"))); // NOI18N
        jLabel10.setText("meat 3");

        mainMenuButton3.setBackground(new java.awt.Color(255, 255, 0));
        mainMenuButton3.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        mainMenuButton3.setText("Main Menu");
        mainMenuButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        mainMenuButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainMenuButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButton3ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food Catalog Pictures/Lamb.jpg"))); // NOI18N
        jLabel11.setText("meat 1");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food Catalog Pictures/Chicken.jpg"))); // NOI18N
        jLabel12.setText("meat 2");
        jLabel12.setToolTipText("");

        javax.swing.GroupLayout meatsJPanelLayout = new javax.swing.GroupLayout(meatsJPanel);
        meatsJPanel.setLayout(meatsJPanelLayout);
        meatsJPanelLayout.setHorizontalGroup(
            meatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meatsJPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(meatsJPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(meatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quitlJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenuButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(meatsJPanelLayout.createSequentialGroup()
                        .addComponent(lambMuttonRB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(chickenRB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(duckRB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        meatsJPanelLayout.setVerticalGroup(
            meatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meatsJPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(meatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(meatsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chickenRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lambMuttonRB)
                    .addComponent(duckRB))
                .addGap(36, 36, 36)
                .addComponent(viewJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainMenuButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quitlJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(meatsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(meatsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lambMuttonRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lambMuttonRBActionPerformed
        // changing radio buttons to select only one
        if (lambMuttonRB.isSelected()){
            chickenRB.setSelected(false);
            duckRB.setSelected(false);
        }
    }//GEN-LAST:event_lambMuttonRBActionPerformed

    private void duckRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duckRBActionPerformed
        // changing radio buttons so only one is selected
        if (duckRB.isSelected()){
            chickenRB.setSelected(false);
            lambMuttonRB.setSelected(false);
        }
    }//GEN-LAST:event_duckRBActionPerformed

    private void chickenRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenRBActionPerformed
        // changing radio buttons so only one is selected

        if (chickenRB.isSelected()){
            lambMuttonRB.setSelected(false);
            duckRB.setSelected(false);
        }
    }//GEN-LAST:event_chickenRBActionPerformed

    private void quitlJLabel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitlJLabel3ActionPerformed
        // cancel
        System.exit(0);
    }//GEN-LAST:event_quitlJLabel3ActionPerformed

    private void viewJLabel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJLabel4ActionPerformed

        if (lambMuttonRB.isSelected()){
            JOptionPane.showMessageDialog(null, "");
            dispose();
            MeatsJDialog obj = new MeatsJDialog();
            obj.setVisible(true);
        }
        else if(chickenRB.isSelected()){
            JOptionPane.showMessageDialog(null, "");
            dispose();
            MeatsJDialog obj = new MeatsJDialog();
            obj.setVisible(true);
        }
        else if(duckRB.isSelected()){
            JOptionPane.showMessageDialog(null, "Duck meat is derived primarily from the breasts and legs of ducks. "
                    + "\nAs all poultry meat, the meat is categorically classed as white meat despite the colour being slightly darker than normal poultry. "
                    + "\nThe meat of the legs is darker and somewhat fattier than the meat of the breasts, "
                    + "\nalthough the breast meat is darker than the breast meat of a chicken or a turkey. "
                    + "\nBeing waterfowl, ducks have a layer of heat-insulating subcutaneous fat between the skin and the meat."
                    + "De-boned duck breast can be grilled like steak, usually leaving the skin and fat on. "
                    + "Internal organs such as heart and kidneys may also be eaten; "
                    + "the liver in particular is often used as a substitute for goose liver in foie gras.");
            dispose();
            MeatsJDialog obj = new MeatsJDialog();
            obj.setVisible(true);
        }
    }//GEN-LAST:event_viewJLabel4ActionPerformed

    private void clearJLabel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJLabel4ActionPerformed
        //      clears all selections and text fields
        lambMuttonRB.setSelected(false);
        chickenRB.setSelected(false);
        duckRB.setSelected(false);
    }//GEN-LAST:event_clearJLabel4ActionPerformed

    private void mainMenuButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButton3ActionPerformed

        dispose();
        MainMenuJDialog obj = new MainMenuJDialog();
        obj.setVisible(true);
    }//GEN-LAST:event_mainMenuButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeatsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeatsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeatsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeatsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeatsJDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton chickenRB;
    private javax.swing.JButton clearJLabel4;
    private javax.swing.JRadioButton duckRB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JRadioButton lambMuttonRB;
    private javax.swing.JButton mainMenuButton3;
    private javax.swing.JPanel meatsJPanel;
    private javax.swing.JButton quitlJLabel3;
    private javax.swing.JButton viewJLabel4;
    // End of variables declaration//GEN-END:variables
}
