/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcatalog;

import javax.swing.JOptionPane;

/**
 *
 * @author sasmith10
 */
public class PastriesJDialog extends javax.swing.JDialog {

    /**
     * Creates new form FoodJDialog
     */
    public PastriesJDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pastriesJPanel = new javax.swing.JPanel();
        baklavaRB = new javax.swing.JRadioButton();
        macaronRB = new javax.swing.JRadioButton();
        croissantRB = new javax.swing.JRadioButton();
        quitlJLabel3 = new javax.swing.JButton();
        viewJLabel4 = new javax.swing.JButton();
        clearJLabel4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        mainMenuButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pastriesJPanel.setBackground(new java.awt.Color(204, 0, 0));
        pastriesJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Pastry Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Showcard Gothic", 2, 46), new java.awt.Color(255, 255, 0))); // NOI18N

        baklavaRB.setBackground(new java.awt.Color(255, 255, 0));
        baklavaRB.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        baklavaRB.setText("Baklava");
        baklavaRB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        baklavaRB.setBorderPainted(true);
        baklavaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baklavaRBActionPerformed(evt);
            }
        });

        macaronRB.setBackground(new java.awt.Color(255, 255, 0));
        macaronRB.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        macaronRB.setText("Macaron");
        macaronRB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        macaronRB.setBorderPainted(true);
        macaronRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                macaronRBActionPerformed(evt);
            }
        });

        croissantRB.setBackground(new java.awt.Color(255, 255, 0));
        croissantRB.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        croissantRB.setText("Croissant");
        croissantRB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        croissantRB.setBorderPainted(true);
        croissantRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croissantRBActionPerformed(evt);
            }
        });

        quitlJLabel3.setBackground(new java.awt.Color(255, 255, 0));
        quitlJLabel3.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        quitlJLabel3.setText("Quit");
        quitlJLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        quitlJLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitlJLabel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitlJLabel3ActionPerformed(evt);
            }
        });

        viewJLabel4.setBackground(new java.awt.Color(255, 255, 0));
        viewJLabel4.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        viewJLabel4.setText("View Item");
        viewJLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        viewJLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewJLabel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJLabel4ActionPerformed(evt);
            }
        });

        clearJLabel4.setBackground(new java.awt.Color(255, 255, 0));
        clearJLabel4.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        clearJLabel4.setText("Clear");
        clearJLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        clearJLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearJLabel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJLabel4ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food Catalog Pictures/Macaron.jpg"))); // NOI18N
        jLabel10.setText("Pastry 3");

        mainMenuButton3.setBackground(new java.awt.Color(255, 255, 0));
        mainMenuButton3.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        mainMenuButton3.setText("Main Menu");
        mainMenuButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        mainMenuButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainMenuButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButton3ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food Catalog Pictures/baklava_50_1_50_2_02.jpg"))); // NOI18N
        jLabel11.setText("Pastry 1");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food Catalog Pictures/Croissant.jpg"))); // NOI18N
        jLabel12.setText("Pastry 2");
        jLabel12.setToolTipText("");

        javax.swing.GroupLayout pastriesJPanelLayout = new javax.swing.GroupLayout(pastriesJPanel);
        pastriesJPanel.setLayout(pastriesJPanelLayout);
        pastriesJPanelLayout.setHorizontalGroup(
            pastriesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pastriesJPanelLayout.createSequentialGroup()
                .addGroup(pastriesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pastriesJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pastriesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainMenuButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quitlJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pastriesJPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(baklavaRB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(croissantRB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(macaronRB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(pastriesJPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        pastriesJPanelLayout.setVerticalGroup(
            pastriesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pastriesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pastriesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pastriesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(croissantRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(baklavaRB)
                    .addComponent(macaronRB))
                .addGap(36, 36, 36)
                .addComponent(viewJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainMenuButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quitlJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pastriesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pastriesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baklavaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baklavaRBActionPerformed
        // changing radio buttons to select only one
        if (baklavaRB.isSelected()){
            croissantRB.setSelected(false);
            macaronRB.setSelected(false);
        }
    }//GEN-LAST:event_baklavaRBActionPerformed

    private void macaronRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_macaronRBActionPerformed
        // changing radio buttons so only one is selected
        if (macaronRB.isSelected()){
            croissantRB.setSelected(false);
            baklavaRB.setSelected(false);
        }
    }//GEN-LAST:event_macaronRBActionPerformed

    private void croissantRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croissantRBActionPerformed
        // changing radio buttons so only one is selected

        if (croissantRB.isSelected()){
            baklavaRB.setSelected(false);
            macaronRB.setSelected(false);
        }
    }//GEN-LAST:event_croissantRBActionPerformed

    private void quitlJLabel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitlJLabel3ActionPerformed
        // cancel
        System.exit(0);
    }//GEN-LAST:event_quitlJLabel3ActionPerformed

    private void viewJLabel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJLabel4ActionPerformed

        if (baklavaRB.isSelected()){
            JOptionPane.showMessageDialog(null, "Baklava is a rich, sweet dessert pastry made of layers of filo filled with chopped"
                    + "\nnuts and sweetened and held together with syrup or honey. "
                    + "\nIt is characteristic of the cuisines of the Levant and the broader Middle East, "
                    + "\nalong with Greece, the South Caucasus, Balkans, Maghreb, and Central Asia.");
            dispose();
            PastriesJDialog obj = new PastriesJDialog();
            obj.setVisible(true);
        }
        else if(croissantRB.isSelected()){
            JOptionPane.showMessageDialog(null, "A croissant is a buttery, flaky, viennoiserie pastry of Austrian origin, "
                    + "\nnamed for its historical crescent shape. Croissants and other viennoiserie are made of a layered yeast-leavened dough.");
            dispose();
            PastriesJDialog obj = new PastriesJDialog();
            obj.setVisible(true);
        }
        else if(macaronRB.isSelected()){
            JOptionPane.showMessageDialog(null, "A macaron or French macaroon is a sweet meringue-based confection "
                    + "\nmade with egg white, icing sugar, granulated sugar, almond meal, and food coloring. "
                    + "\nThere is some variation in whether the term macaron or macaroon is used, and the related coconut macaroon is often confused with the macaron.");
            dispose();
            PastriesJDialog obj = new PastriesJDialog();
            obj.setVisible(true);
        }
    }//GEN-LAST:event_viewJLabel4ActionPerformed

    private void clearJLabel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJLabel4ActionPerformed
        //      clears all selections and text fields
        baklavaRB.setSelected(false);
        croissantRB.setSelected(false);
        macaronRB.setSelected(false);
    }//GEN-LAST:event_clearJLabel4ActionPerformed

    private void mainMenuButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButton3ActionPerformed

        dispose();
        MainMenuJDialog obj = new MainMenuJDialog();
        obj.setVisible(true);
    }//GEN-LAST:event_mainMenuButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PastriesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PastriesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PastriesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PastriesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PastriesJDialog().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton baklavaRB;
    private javax.swing.JButton clearJLabel4;
    private javax.swing.JRadioButton croissantRB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JRadioButton macaronRB;
    private javax.swing.JButton mainMenuButton3;
    private javax.swing.JPanel pastriesJPanel;
    private javax.swing.JButton quitlJLabel3;
    private javax.swing.JButton viewJLabel4;
    // End of variables declaration//GEN-END:variables
}
