/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcatalog;

import javax.swing.JOptionPane;

/**
 *
 * @author sasmith10
 */
public class SaladsJDialog extends javax.swing.JFrame {

    /**
     * Creates new form SaladsJDialog
     */
    public SaladsJDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saladsJPanel = new javax.swing.JPanel();
        caesarRB = new javax.swing.JRadioButton();
        panzanellaRB = new javax.swing.JRadioButton();
        eggRB = new javax.swing.JRadioButton();
        quitlJLabel3 = new javax.swing.JButton();
        viewJLabel4 = new javax.swing.JButton();
        clearJLabel4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        mainMenuButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        saladsJPanel.setBackground(new java.awt.Color(204, 0, 0));
        saladsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Salad Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Showcard Gothic", 2, 46), new java.awt.Color(255, 255, 0))); // NOI18N

        caesarRB.setBackground(new java.awt.Color(255, 255, 0));
        caesarRB.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        caesarRB.setText("Caesar");
        caesarRB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        caesarRB.setBorderPainted(true);
        caesarRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caesarRBActionPerformed(evt);
            }
        });

        panzanellaRB.setBackground(new java.awt.Color(255, 255, 0));
        panzanellaRB.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        panzanellaRB.setText("Panzanella");
        panzanellaRB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panzanellaRB.setBorderPainted(true);
        panzanellaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panzanellaRBActionPerformed(evt);
            }
        });

        eggRB.setBackground(new java.awt.Color(255, 255, 0));
        eggRB.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        eggRB.setText("egg");
        eggRB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        eggRB.setBorderPainted(true);
        eggRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eggRBActionPerformed(evt);
            }
        });

        quitlJLabel3.setBackground(new java.awt.Color(255, 255, 0));
        quitlJLabel3.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        quitlJLabel3.setText("Quit");
        quitlJLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        quitlJLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitlJLabel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitlJLabel3ActionPerformed(evt);
            }
        });

        viewJLabel4.setBackground(new java.awt.Color(255, 255, 0));
        viewJLabel4.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        viewJLabel4.setText("View Item");
        viewJLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        viewJLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewJLabel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJLabel4ActionPerformed(evt);
            }
        });

        clearJLabel4.setBackground(new java.awt.Color(255, 255, 0));
        clearJLabel4.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        clearJLabel4.setText("Clear");
        clearJLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        clearJLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearJLabel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJLabel4ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food Catalog Pictures/Panzanella.jpeg"))); // NOI18N
        jLabel10.setText("salad 3");

        mainMenuButton3.setBackground(new java.awt.Color(255, 255, 0));
        mainMenuButton3.setFont(new java.awt.Font("Showcard Gothic", 2, 11)); // NOI18N
        mainMenuButton3.setText("Main Menu");
        mainMenuButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        mainMenuButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainMenuButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButton3ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food Catalog Pictures/Caesar.jpg"))); // NOI18N
        jLabel11.setText("salad 1");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Food Catalog Pictures/Egg.jpg"))); // NOI18N
        jLabel12.setText("salad 2");
        jLabel12.setToolTipText("");

        javax.swing.GroupLayout saladsJPanelLayout = new javax.swing.GroupLayout(saladsJPanel);
        saladsJPanel.setLayout(saladsJPanelLayout);
        saladsJPanelLayout.setHorizontalGroup(
            saladsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saladsJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(saladsJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(caesarRB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(saladsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saladsJPanelLayout.createSequentialGroup()
                        .addComponent(eggRB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(panzanellaRB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(viewJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenuButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitlJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        saladsJPanelLayout.setVerticalGroup(
            saladsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saladsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saladsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(saladsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caesarRB)
                    .addComponent(eggRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panzanellaRB))
                .addGap(38, 38, 38)
                .addComponent(viewJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainMenuButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quitlJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saladsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saladsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caesarRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caesarRBActionPerformed
        // changing radio buttons to select only one
        if (caesarRB.isSelected()){
            eggRB.setSelected(false);
            panzanellaRB.setSelected(false);
        }
    }//GEN-LAST:event_caesarRBActionPerformed

    private void panzanellaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panzanellaRBActionPerformed
        // changing radio buttons so only one is selected
        if (panzanellaRB.isSelected()){
            eggRB.setSelected(false);
            caesarRB.setSelected(false);
        }
    }//GEN-LAST:event_panzanellaRBActionPerformed

    private void eggRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eggRBActionPerformed
        // changing radio buttons so only one is selected

        if (eggRB.isSelected()){
            caesarRB.setSelected(false);
            panzanellaRB.setSelected(false);
        }
    }//GEN-LAST:event_eggRBActionPerformed

    private void quitlJLabel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitlJLabel3ActionPerformed
        // cancel
        System.exit(0);
    }//GEN-LAST:event_quitlJLabel3ActionPerformed

    private void viewJLabel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJLabel4ActionPerformed

        if (caesarRB.isSelected()){
            JOptionPane.showMessageDialog(null, "A Caesar salad is a green salad of romaine lettuce and croutons dressed with lemon juice, "
                    + "\nolive oil, egg, Worcestershire sauce, anchovies, garlic, Dijon mustard, Parmesan cheese, and black pepper. "
                    + "\nIn its original form, this salad was prepared and served tableside. "
                    + "\nAlthough the original recipe does not contain anchovies, "
                    + "\nmodern recipes typically include anchovies as a key ingredient, which frequently is emulsified in bottled versions.");
            dispose();
            SaladsJDialog obj = new SaladsJDialog();
            obj.setVisible(true);
        }
        else if(eggRB.isSelected()){
            JOptionPane.showMessageDialog(null, "Egg salad is a dish made primarily of chopped hard-boiled eggs and mayonnaise, "
                    + "\noften including other ingredients such as celery or mustard, which is frequently used as a sandwich spread. "
                    + "\nIt is made mixed with seasonings in the form of herbs, spices and other ingredients, bound with mayonnaise. "
                    + "\nEgg salad can be made creatively with any number of other cold foods added. "
                    + "\nBacon, bell pepper, capers, cheese, cucumber, onions, lettuce, pickle relish and pickles are common additional ingredients.");
            dispose();
            SaladsJDialog obj = new SaladsJDialog();
            obj.setVisible(true);
        }
        else if(panzanellaRB.isSelected()){
            JOptionPane.showMessageDialog(null, "Panzanella or panmolle is a Tuscan chopped salad of soaked stale bread, "
                    + "\nonions and tomatoes that is popular in the summer. It often includes cucumbers, sometimes basil and is dressed with olive oil and vinegar."
                    + "\nIt is also popular in other parts of central Italy. The 16th-century artist and poet Bronzino sings the praises of onions with oil and vinegar "
                    + "\nserved with toast and, a page later, speaks of a salad of onions, purslane, and cucumbers. "
                    + "\nThis is often interpreted as a description of panzanella."
                    + "\nThe name is believed to be a portmanteau of \"pane\", Italian for bread, and \"zanella\", a deep plate in which it is served.");
            dispose();
            SaladsJDialog obj = new SaladsJDialog();
            obj.setVisible(true);
        }
    }//GEN-LAST:event_viewJLabel4ActionPerformed

    private void clearJLabel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJLabel4ActionPerformed
        //      clears all selections and text fields
        caesarRB.setSelected(false);
        eggRB.setSelected(false);
        panzanellaRB.setSelected(false);
    }//GEN-LAST:event_clearJLabel4ActionPerformed

    private void mainMenuButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButton3ActionPerformed

        dispose();
        MainMenuJDialog obj = new MainMenuJDialog();
        obj.setVisible(true);
    }//GEN-LAST:event_mainMenuButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaladsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaladsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaladsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaladsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaladsJDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton caesarRB;
    private javax.swing.JButton clearJLabel4;
    private javax.swing.JRadioButton eggRB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JButton mainMenuButton3;
    private javax.swing.JRadioButton panzanellaRB;
    private javax.swing.JButton quitlJLabel3;
    private javax.swing.JPanel saladsJPanel;
    private javax.swing.JButton viewJLabel4;
    // End of variables declaration//GEN-END:variables
}
